# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9cc72d59893b4377787b0d2351033cc0e0094800edfce7a4c1b9c8c42b9f080d7b39aebec29f9237178536eec4f74ca0f9134cd885768e539dde085a25cca739

test:
  secret_key_base: 81e7697324481cc1d989d33ca2010694562f1f736442770b15aa9b782076abbe3eaf648372c4747ad76caceb6c77015a17c08d0e788882d2d29c51976057a428

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
